# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveGetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveIteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default=b'switch', max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('SN', models.CharField(blank=True, max_length=200)),
                ('asset_id', models.CharField(blank=True, max_length=200)),
                ('bin', models.CharField(blank=True, max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.ReceiveGetting')),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Ofa_receiving', models.BooleanField(default=False)),
                ('creator', models.CharField(default=b'bwwa', max_length=100)),
                ('tracking_number', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('po', models.CharField(max_length=200)),
                ('rma_id', models.CharField(max_length=200)),
                ('place_location', models.CharField(max_length=200)),
                ('short_desc', models.CharField(max_length=200)),
                ('comment', models.TextField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name=b'Time')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Category')),
                ('courier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Courier')),
            ],
        ),
        migrations.CreateModel(
            name='ShipIteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default=b'switch', max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('SN', models.CharField(blank=True, max_length=200)),
                ('asset_id', models.CharField(blank=True, max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('note', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=b'bwwa', max_length=100, verbose_name=b'Creator')),
                ('tracking_number', models.CharField(max_length=200, verbose_name=b'Tracking Number')),
                ('vendor', models.CharField(max_length=200, verbose_name=b'Vendor')),
                ('po', models.CharField(max_length=200, verbose_name=b'PO')),
                ('rma_id', models.CharField(max_length=200, verbose_name=b'RMA ID')),
                ('short_desc', models.CharField(max_length=200, verbose_name=b'Short Description')),
                ('comment', models.TextField(max_length=200, verbose_name=b'Comment')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name=b'Create Time')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Category', verbose_name=b'Category')),
                ('courier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Courier')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('to_list', models.EmailField(max_length=100)),
                ('cc_list', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='shipping',
            name='site_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Site', verbose_name=b'Site'),
        ),
        migrations.AddField(
            model_name='shipiteam',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Shipping'),
        ),
        migrations.AddField(
            model_name='receiving',
            name='site_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Site'),
        ),
        migrations.AddField(
            model_name='receiveiteam',
            name='receiving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Receiving'),
        ),
    ]
