# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivegetting',
            name='info',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
